### ISSUE TITLE
make first object as selected in button title

### ISSUE THREAD

**Issue by aravindhrbt** [sohobloo/react-native-modal-dropdown#36]
Hi @sohobloo,

   
I have state variable {countryListDropDown: []} to hold dropdown data, initially it will be empty,in componentWillMount i make api call and update the state variable with data  {countryListDropDown: ['canada','united states']},

```
<ModalDropdown
                    defaultValue = {this.state.countryListDropDown.length > 0 ? this.state.countryListDropDown[0] : 'select country..'}
                    defaultIndex = {this.state.countryListDropDown.length > 0 ? 0 : -1}
                    textStyle = {{color:'#a0adb3',fontSize:20}}
                    dropdownStyle = {{width:windowSize.width-40,borderWidth:2}}
                    style={{height:40,paddingTop:10}}
                    options={this.state.countryListDropDown}
                    onSelect={(idx, value) => this.onCountrySelection(idx, value)}
                    />
```

**how to make the 0th object as default selection? i tried with default index it selects in dropdown container but i need to update the button title from 'select country..' to 'canada'.**

**Comment by sohobloo** [comment]
First of all, changing defaultXXX can only affect the initial state of the component. Since you updated your options after initial, you have to manually change the index following the steps below:

1. Make a ref.
`<ModalDropdown ref='dropdown' ... />`

2. You can call `dropdown.select(0)` after your country list data updated.  
You can find the usage of `select(idx)` in readme: 
select(idx)	Select the specified option of the idx. Select -1 will reset it to display defaultValue. Won't trigger onSelect.

Then, your `defaultValue` can just set to 'select country..'.

**Comment by aravindhrbt** [comment]
Thanks a lot @sohobloo 💯 

It works 
Here is my working Code 

            ```
      <ModalDropdown
                    ref = 'countryModal'
                    defaultValue = 'Select Country'
                    textStyle = {{color:'#a0adb3',fontSize:20}}
                    dropdownStyle = {{width:windowSize.width-40,borderWidth:2}}
                    style={{height:40,paddingTop:10}}
                    options={this.state.countryListDropDown}
                    onSelect={(idx, value) => this.onCountrySelection(idx, value)}
                    />
```

and in api success response , i am checking the array length and updating my ref
```
if (this.state.countryListDropDown.length > 0) {
            this.refs.countryModal.select(0);
          }
```
