### ISSUE TITLE
Status bar covered, how to disable

### ISSUE THREAD

**Issue by brascene** [sohobloo/react-native-modal-dropdown#50]
Hi, after clicking on dropdown,  status bar is changed, like backdrop is there and it's covering whole screen on Android, including status bar. I dont' want status bar to be affected at all while clicking on dropdown, how can this be achieved?
Thanks in advance!

**Comment by sohobloo** [comment]
@brascene This is a behavior of `Modal` component of react native and I don't know how to solve your problem. Sorry!
By the way, `Modal` indeed has some style issues in Android like [this one](https://github.com/facebook/react-native/issues/7474), in which says:
>  Modal is implemented with Dialog, Dialog will create a window on the top of Activity's Window.

**Comment by farzadab** [comment]
@sohobloo I have an idea, you can use [react-native-simple-modal](https://github.com/bodyflex/react-native-simple-modal), since it doesn't cover the Status Bar.
Unfortunately, It's **not** a drop-in replacement for RN Modal component, but it shouldn't be hard to make it work. I can try to do it, but I might not be able to get the details right.

**Comment by sohobloo** [comment]
@farzadab Thanks for the suggestion. Worth trying.
