### ISSUE TITLE
Issue with resetting to default 

### ISSUE THREAD

**Issue by zach5410** [sohobloo/react-native-modal-dropdown#97]
I have two dropdown boxes.  The one is an array of filters  The other has predetermined data being passed through depending on the filter.

Here is an example of what happens:
I select Filter A from `filter drop down` menu.  In the `data drop down` I pick data point A.  BUT, lets say that I change my mind and change the filter in the `filter drop down` to Filter B.  The selected data point remains in the `data drop down` box, and does not reset to the default text.  

I am passing the filters through to Redux, so my props is changing, I am seeing that the data is changing.  But my component is not rerendering.  

Thoughts?

**Comment by simjoh** [comment]
I'm also interested of this feature.

**Comment by simjoh** [comment]
I think I solved this at least for myself. But I'm not using redux so it might not help you @zach5410. 
I've one Region dropdown that filters a cities dropdown. I will try to explain how I solved it. But I stripped down the ModalDropdown to only show the some content. So you might need to think a little to get it to work butt is really simple!

```
<ModalDropdown options={this.state.regions}
                              showVerticalScrollIndicator={true}
                              defaultIndex={-1}
                              defaultValue={this.state.default_region}
                              onSelect={(idx, value) => this._dropdown_onSelect_region(idx, value)}
              />

<ModalDropdown  ref='cities' <----- THIS IS ADDED to be able to call the dropdown select()
                              options={this.state.cities}
                              defaultIndex={-1}
                              defaultValue={this.state.default_city}
                              onSelect={(idx, value) => this._dropdown_onSelect_city(idx, value)}
              />
```

In my function dropdown_onSelect_region(idx,value) which is called onSelect. I added the following line att the end. 

`this.refs['cities'].select(-1);`

This is of course a quite stupid implementation since the choice of city will change to default even if the same region is choosen twice.

**Comment by zach5410** [comment]
@simjoh I actually figured this out.  The issue is that by default the drop downs do not automatically reset when the component is rerendered.  

Somewhere in the documentation I finally figured it out.  At the bottom he states that there are 3 functions that you can call,one being a selectidx() (I think) function.  

If you pass -1 through to the selectidx() function, then it resets the drop-down.  

Hope this helps!

**Comment by nikasvan** [comment]
@zach5410 Could you exactly elaborate on this:

> Somewhere in the documentation I finally figured it out. At the bottom he states that there are 3 functions that you can call,one being a selectidx() (I think) function.

I used selectidx as prop to modaldropdown component and passed -1 but not working. Could you let us know how are you achieving dropdown reset? Thanks
